language: csharp
dist: bionic
mono: none
#must declare version
dotnet: 2.2.401
script:
 - dotnet pack ./solution/NPOI.Core.sln -c Release --output $TRAVIS_BUILD_DIR/build
 - cd $TRAVIS_BUILD_DIR/build
 - ls *.nupkg
 - if [ -f "$PKG_NAME" ]; then for f in *.nupkg ; do dotnet nuget push $f -k $NUGET_TOKEN -s https://api.nuget.org/v3/index.json; done; fi
